{{- if and .Values.rbac.create (eq (include "crunchy-userinit.needsClusterRBAC" .) "true") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "crunchy-userinit.fullname" . }}"
  labels:
    {{- include "crunchy-userinit.labels" . | nindent 4 }}
rules:
  # Framework: posting events about handler progress/errors
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # Needed to read secrets across namespaces
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "crunchy-userinit.fullname" . }}"
  labels:
    {{- include "crunchy-userinit.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "crunchy-userinit.fullname" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "crunchy-userinit.serviceAccountName" . }}"
    namespace: "{{ .Release.Namespace }}"
{{- end -}}
