[tools]
helm = "3.17.4"
helm-docs = "1.14.2"
kind = "0.29.0"
uv = "0.7.20"

# Python Related
[tasks.test]
description = "Run the test suite"
run = "uv run pytest"

[tasks.coverage-ui]
description = "Run the test suite with coverage with html view"
run = ["uv run pytest", "python -m webbrowser .coverage/htmlcov/index.html"]

[tasks.lint]
description = "Run the linter"
run = "uv run ruff check"

[tasks.lint-fix]
description = "Run the linter with fix"
run = "uv run ruff check --fix"

[tasks.format]
description = "Run the formatter"
run = "uv run ruff format"

# Chart Related
[tasks.helm-docs]
description = "Generate helm docs"
run = "helm-docs --chart-search-root charts"

[tasks.helm-test]
description = "Run helm tests"
run = "helm unittest charts/crunchy-userinit"

# Docker Related
[tasks.docker-build]
description = "Build the docker image"
run = "docker build . -t drummyfloyd/crunchy-userinit-controller:dev"

# Local Dev/Testing Related
[tasks.local-env]
description = "Deploy the dev environment with kind cluster and crunchydata operator"
run = "src/tests/integration/deploy.sh -c"

[tasks.local-run]
description = "Run controller locally"
run = 'kopf run --namespace {{arg(name="namespace",default="postgres")}} -m userinit.userinit'
env = {DEV_MODE = "true"}
dir = "{{cwd}}/src"

[tasks.local-test]
description = "Run local controller with kind cluster (configured)"
run = "mise run local-env"
depends_post = "local-run"

[tasks.local-destroy]
description = "Destroy the local dev environment"
run = "src/tests/integration/deploy.sh -d"
