---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  configAnnotation: crunchy-userinit.ramblurr.github.com/last-handled-configuration
  configEscapedAnnotation: crunchy-userinit\.ramblurr\.github\.com/last-handled-configuration
  managedAnnotation: crunchy-userinit.ramblurr.github.com/kopf-managed
  managedEscapedAnnotation: crunchy-userinit\.ramblurr\.github\.com/kopf-managed
  #annotation: kopf.zalando.org/last-handled-configuration
  #escapedAnnotation: kopf\.zalando\.org/last-handled-configuration
tasks:
  dev:run:
    cmd: |
      kopf run --dev -n database userinit.py
  dev:reset:
    cmd: |
      kubectl get secrets -n database -o jsonpath="{range .items[?(@.metadata.annotations.{{.configEscapedAnnotation}})]}{.metadata.name}{'\n'}{end}" | xargs -I {} kubectl -n database annotate secrets '{}' {{.configAnnotation}}-
      kubectl get secrets -n database -o jsonpath="{range .items[?(@.metadata.annotations.{{.managedEscapedAnnotation}})]}{.metadata.name}{'\n'}{end}" | xargs -I {} kubectl -n database annotate secrets '{}' {{.managedAnnotation}}-
