# -- Set number of replicas
replicaCount: 1

image:
  # -- Container image repository
  repository: ghcr.io/ramblurr/crunchy-userinit-controller
  # -- Container image pull policy
  pullPolicy: IfNotPresent
  # -- Container image tag (immutable tags are recommended)
  tag: "main@sha256:0970b9b9c919bd87dcb72d9d5b940faf2b128128899a132ec963e2860595f4a6"

# -- Additional environment variables to apply to the main pod
extraEnv: []
#  - name: DEV_MODE_
#    value: true

# -- Specify docker-registry secret names as an array
imagePullSecrets: []

# -- String to partially override crunchy-userinit-controller.fullname template
nameOverride: ""

# -- String to fully override crunchy-userinit-controller.fullname template
fullnameOverride: ""

# -- Service account configuration (required for the controller to function)
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations to add to the pod
podAnnotations: {}

# -- Labels to add to the pod
podLabels: {}

# -- Configure pod security context
podSecurityContext: {}

# -- Configure container security context
securityContext: {}

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 80

# -- Resource limits and requests for the controller pod
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Additional volumes on the output Deployment definition
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}
