name: (Chart) Release

on:
  push:
    tags:
      - "chart*"
  workflow_dispatch:
  workflow_call:
    inputs:
      new-tag:
        required: true
        type: string
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          linting: off
