---
name: (Docker) Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "src/userinit/*.py"
      - "src/entrypoint.sh"
      - "Dockerfile"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - "src/userinit/*.py"
      - "src/entrypoint.sh"
      - "Dockerfile"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "build-date=${build_date}" >> "$GITHUB_OUTPUT"
          echo "git-hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Debug
        run: |
          echo "${{ steps.vars.outputs.build-date }}"
          echo "${{ stets.vars.outputs.git-hash }}"

      #platforms: linux/amd64,linux/arm64
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.build-date }}
            GIT_HASH=${{ steps.vars.outputs.git-hash }}
