---
name: (Python) Unittest & Coverage

on:
  pull_request:
    # types: [review_requested, ready_for_review]
    paths:
      - "src/**/*.py"
      - pyproject.toml
      - .python-version
      - "uv.lock"
      - .python-version
  push:
    branches:
      - main
    paths:
      - "src/**/*.py"
      - pyproject.toml
      - .python-version
      - "uv.lock"
      - .python-version

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4
        with:
          install: true
          cache: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest and coverage
        run: |
          set -o pipefail
          mise run ci-test | tee pytest-coverage.txt

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@fd9adbdca9fdfbe2b9bfa44a7340e6a83346ce6c # main
        with:
          junitxml-path: .coverage/junit.xml
          title: Coverage Report
          hide-report: false
