---
name: (Python) Unittest & Coverage

on:
  pull_request:
    # types: [review_requested, ready_for_review]
    paths:
      - "src/**/*.py"
      - pyproject.toml
      - .python-version
      - "uv.lock"
      - .python-version
  push:
    branches:
      - main
    paths:
      - "src/**/*.py"
      - pyproject.toml
      - .python-version
      - "uv.lock"
      - .python-version

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4
        with:
          install: true
          cache: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest and coverage
        run: |
          set -o pipefail
          mise run ci-test | tee pytest-coverage.txt

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@09c28b6767e12a048e0b23e821ed03133ee48a1a # main
        with:
          junitxml-path: .coverage/junit.xml
          title: Coverage Report
          hide-report: false
